export const GET_AUTHORS = 'GET_AUTHORS';
export const SAVE_AUTHOR = 'SAVE_AUTHOR';
export const FILTER_AUTHORS_WHEN_REMOVED = 'FILTER_AUTHORS_WHEN_REMOVED';
export const FILTER_AUTHORS_WHEN_SELECTED = 'FILTER_AUTHORS_WHEN_SELECTED';
export const SET_AUTHORS_ERROR = 'SET_AUTHORS_ERROR';
